# 10% do total de pods obrigatoriamente 
# devem esperar a criação de novos pods 
# para então serem migrados por qualquer motivo de vazão
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: demo-pdb
  namespace: default
spec:
  maxUnavailable: 10%
  selector:
    matchLabels:
      app: demo

 