# Mínimo de 3 pods disponíveis para vazão 
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: demo-pdb
  namespace: default
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: demo

 