apiVersion: v1
kind: LimitRange
metadata:
  name: LimitRangeName
  namespace: solution-x
spec:
  limits:
  - type: Container
    default:
      cpu: 100m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    max:
      cpu: 200m
      memory: 512Mi
    min:
      cpu: 100m
      memory: 256Mi
