apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      name: hello-world
      namespace: default
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: hello-world
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort:  8080
          name:  http
      restartPolicy: Always