apiVersion: v1
kind: Service
metadata:
  name: numeros-por-extenso-service
  namespace: default
spec:
  selector:
    app: numeros-por-extenso
  ports:
  - name: https
    port: 8888
    targetPort: 8080
    